### ISSUE TITLE
比賽結構面板錯誤 Cannot read properties of undefined (reading 'find') 

### ISSUE THREAD

**Issue by Otmeal** [NYCUarchery/archeryWebsite#112]
因為 #111 的改動產生。|

TypeError: Cannot read properties of undefined (reading 'find')
    at extractEliminationID (http://localhost/scoring/src/features/AdministrationBoard/GameStructureBoard/GameStructureBoard.tsx:134:24)
    at GameStructureBoard (http://localhost/scoring/src/features/AdministrationBoard/GameStructureBoard/GameStructureBoard.tsx:46:25)
    at renderWithHooks (http://localhost/scoring/node_modules/.vite/deps/chunk-GSZ7ISAW.js?v=421afe30:12171:26)
    at updateFunctionComponent (http://localhost/scoring/node_modules/.vite/deps/chunk-GSZ7ISAW.js?v=421afe30:14577:28)
    at beginWork (http://localhost/scoring/node_modules/.vite/deps/chunk-GSZ7ISAW.js?v=421afe30:15912:22)
    at beginWork$1 (http://localhost/scoring/node_modules/.vite/deps/chunk-GSZ7ISAW.js?v=421afe30:19749:22)
    at performUnitOfWork (http://localhost/scoring/node_modules/.vite/deps/chunk-GSZ7ISAW.js?v=421afe30:19194:20)
    at workLoopSync (http://localhost/scoring/node_modules/.vite/deps/chunk-GSZ7ISAW.js?v=421afe30:19133:13)
    at renderRootSync (http://localhost/scoring/node_modules/.vite/deps/chunk-GSZ7ISAW.js?v=421afe30:19112:15)
    at recoverFromConcurrentError (http://localhost/scoring/node_modules/.vite/deps/chunk-GSZ7ISAW.js?v=421afe30:18732:28)

**Comment by Otmeal** [comment]
Fixed by #113
